# Generated by Django 5.0 on 2023-12-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_item_seller_alter_item_buyer_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(null=True, upload_to='item_photos/<bound method Field.__str__ of <django.db.models.fields.CharField>>'),
        ),
    ]
