# Generated by Django 5.0 on 2023-12-08 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_item_picture'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought_item', to='users.myuser'),
        ),
    ]
